import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "./SideBar";
import { MobileHeader } from "../components";
import Footer from "./Footer";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icon: 'favicon.ico'
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="shortcut icon" type="image/x-icon" href="Logo.ico" />
            </head>
            <body className={poppins.className}>
                <div className="flex">
                    <SideBar />
                    <main className="flex-1">
                        <MobileHeader />
                        {children}
                        <div className="py-20"></div>
                        <Footer />
                    </main>
                </div>
            </body>
        </html>
    );
}
