name: Deploy to Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  

    # - name: Setup SSH
    #   run: |
    #       mkdir -p ~/.ssh
    #       echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/github_actions_key
    #       chmod 600 ~/.ssh/github_actions_key
    #       ssh-keyscan -H 14.225.192.64 >> ~/.ssh/known_hosts

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
    
    - name: Debug SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no nkeyskuo@14.225.192.64 "
          ls -la /var/www &&
          ls -la /var/www/ezticket.io.vn &&
          ls -la /var/www/ezticket.io.vn/frontend
        "

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no nkeyskuo@14.225.192.64 "
          cd /var/www/ezticket.io.vn/frontend && git pull &&
          cd .. &&
          docker-compose down &&
          docker-compose up -d --build
        "