name: Deploy to Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -H 14.225.192.64 >> ~/.ssh/known_hosts

    - name: Copy files to Server
      run: |
        sudo scp -r . nkeyskuo@14.225.192.64:/var/www/ezticket.io.vn/frontend
    
    - name: Deploy with Docker Compose
      run: |
        ssh nkeyskuo@14.225.192.64 'cd /var/www/ezticket.io.vn && docker-compose down && docker-compose up -d --build'